# Generated by Django 3.2 on 2021-12-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='playerBasic',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Nationality', models.CharField(max_length=255)),
                ('Positions', models.CharField(max_length=255)),
                ('Club', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='playerClub',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Club', models.CharField(max_length=255)),
                ('ClubJoined', models.IntegerField()),
            ],
            options={
                'unique_together': {('ID', 'Club')},
            },
        ),
    ]
