# Generated by Django 3.2 on 2021-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0002_playerphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PaceTotal', models.IntegerField()),
                ('ShootingTotal', models.IntegerField()),
                ('PassingTotal', models.IntegerField()),
                ('DribblingTotal', models.IntegerField()),
                ('DefendingTotal', models.IntegerField()),
                ('PhysicalityTotal', models.IntegerField()),
                ('Overall', models.IntegerField()),
                ('Potential', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playerclub',
            name='ClubNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
