# Generated by Django 3.2 on 2021-12-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0004_playerdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerDetail',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=255)),
                ('ValueEUR', models.IntegerField()),
                ('WageEUR', models.IntegerField()),
                ('ClubPosition', models.CharField(max_length=255)),
                ('ClubNumber', models.IntegerField()),
                ('NationalTeam', models.CharField(max_length=255)),
                ('PreferredFoot', models.CharField(max_length=255)),
                ('IntReputation', models.IntegerField()),
                ('AttackingWorkRate', models.CharField(max_length=255)),
                ('DefensiveWorkRate', models.CharField(max_length=255)),
            ],
        ),
    ]
