# Generated by Django 3.2 on 2021-12-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0005_playerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerRating',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('STRating', models.IntegerField()),
                ('LWRating', models.IntegerField()),
                ('LFRating', models.IntegerField()),
                ('CFRating', models.IntegerField()),
                ('RFRating', models.IntegerField()),
                ('RWRating', models.IntegerField()),
                ('CAMRating', models.IntegerField()),
                ('LMRating', models.IntegerField()),
                ('CMRating', models.IntegerField()),
                ('RMRating', models.IntegerField()),
                ('LWBRating', models.IntegerField()),
                ('CDMRating', models.IntegerField()),
                ('RWBRating', models.IntegerField()),
                ('LBRating', models.IntegerField()),
                ('CBRating', models.IntegerField()),
                ('RBRating', models.IntegerField()),
                ('GKRating', models.IntegerField()),
            ],
        ),
    ]
