# Generated by Django 3.2 on 2021-12-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0006_playerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club', models.CharField(max_length=255)),
                ('League', models.CharField(max_length=255)),
                ('LeagueId', models.IntegerField()),
                ('Overall', models.IntegerField()),
                ('Attack', models.IntegerField()),
                ('Midfield', models.IntegerField()),
                ('Defence', models.IntegerField()),
                ('TransferBudget', models.IntegerField()),
                ('DomesticPrestige', models.IntegerField()),
                ('IntPrestige', models.IntegerField()),
                ('Players', models.IntegerField()),
                ('StartingAverageAge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AllTeamAverageAge', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='clubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club', models.CharField(max_length=255)),
                ('club_logo_url', models.CharField(max_length=255)),
            ],
        ),
    ]
