# Generated by Django 3.2 on 2021-12-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0008_auto_20211225_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbasic',
            name='no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerbasic',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballmodel.player'),
        ),
    ]
