# Generated by Django 3.2 on 2021-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballmodel', '0009_auto_20211227_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clubPhoto',
        ),
        migrations.RemoveField(
            model_name='playerbasic',
            name='no',
        ),
        migrations.AddField(
            model_name='clubbasic',
            name='club_logo_url',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerbasic',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
